### ISSUE TITLE
Steamdeck API call implementation possibility

### ISSUE THREAD

**Issue by Thetechnopig** [liamcottle/rustplus-api#10]
Just wondering if I would be able to make http call requests to the server through api linked buttons on a configured streamdeck panel

**Comment by liamcottle** [comment]
Just had a quick look, and there's a NodeJS library for the stream deck. https://www.npmjs.com/package/elgato-stream-deck You should be able to hook up something pretty easy with both libraries.

**Comment by Thetechnopig** [comment]
It looks to be fully redeveloping your code into a stream deck plugin

**Comment by liamcottle** [comment]
Depends what you're trying to achieve. You could do something very simple like this (pseudo code). Which would open and close a door in rust when pressing a button on the stream deck.

```
const RustPlus = require('rustplus-api');
const { openStreamDeck } = require('elgato-stream-deck');

// connect to rust server
var rustplus = new RustPlus('hostname', 28183, 'steamid', 1234567890);

// wait until connected to rust server
rustplus.on('connected', () => {

    // connect to stream deck
    const myStreamDeck = openStreamDeck();
    
    // callback when button is pressed on stream deck
    myStreamDeck.on('up', (keyIndex) => {
	    
        // check what button was pressed on stream deck
        if(keyIndex == 'some-button'){
            rustplus.turnSmartSwitchOn(1234567890); // open door (via smart switch)
        } else if(keyIndex == 'some-other-button') {
            rustplus.turnSmartSwitchOff(1234567890); // close door (via smart switch)
        }

    });

});
```
