### ISSUE TITLE
getting ECONNRESET error

### ISSUE THREAD

**Issue by KuroNoDev** [liamcottle/rustplus-api#4]
I'm having the same issue as [this](https://github.com/expo/expo-cli/issues/519)
Although it's already solved in latest release, my guess is rust companion still uses an older version of expo. It's not directly a bug with this project so feel free to close this issue.

**Comment by liamcottle** [comment]
Hey, are you getting this error when using this project though? Expo isn't used at all for this, as the library connects directly to the Rust Game Server through a websocket.

>It's not directly a bug with this project so feel free to close this issue.

How come you created an issue on this repo then?

**Comment by KuroNoDev** [comment]
It happens when I use the cli pair tool. It does use the expo api. 

> How come you created an issue on this repo then?

There's nowhere else where I can open an issue about this. It wouldn't hurt to let other users know that this doesn't happen only to them.
