### ISSUE TITLE
Are there more possibilities? What is the limit?

### ISSUE THREAD

**Issue by Icezman001** [liamcottle/rustplus-api#9]
Great project! With the project of Nerif-tafu i've been implementing this in a React, mongoDB, node.js project that aims to copy the entire rust+ functionality and add so much more.

I was just wondering from your project, is everything included that you can get from the rustplus api?
Are there other things you can do? More info you can take?
How did you figure out all the data?

Anyway I can help with further expansion of the project or is everything that you can get from rustplus api already covered?

**Comment by liamcottle** [comment]
Cheers mate!

Everything that I could see in the Rust+ mobile app code should be available in this library. If anything is missing, feel free to open an issue or send through a pull request.

You can see the code of the react native expo app if you intercept the http calls made by the Rust+ app when it launches. Or take a look at the [bundle download script](docs/DownloadBundle.md).
